### ISSUE TITLE
Could you please share with me your dataset 

### ISSUE THREAD

**Issue by giangdip2410** [RezaSadeghiWSU/Sleep-quality-in-caregivers#1]
Thank you for your quality paper. Could you please share with me your dataset we use for this paper , so I am able to deeply understand your study. Thank you so much.

**Comment by RezaSadeghiWSU** [comment]
Thank you for reaching out. The data used in this paper have been collected under an accepted Institutional Review Boards (IRB) protocol. Accordingly, we are limited to publishing the original time series. However, we released the final models with the aim of reproducibility and comparability of our models for researchers.

Best Regards,
Reza Sadeghi, PhD
